version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass hoangcn8uetvnu
    volumes:
      - redis-data:/data

volumes:
  redis-data:
